// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint:
        "https://w5eapf55wbcqtf62qrzodbbiqu.appsync-api.eu-north-1.amazonaws.com/graphql",
      region: "eu-north-1",
      defaultAuthMode: "apiKey",
      apiKey: "da2-r4ihppqm7zgifndayyexpyoyb4",
    },
  },
};

export default config;
