# wrangler.toml
name = "next-combine-png"
compatibility_date = "2023-10-26"
compatibility_flags = ["nodejs_compat"]

# 构建输出目录
pages_build_output_dir = ".vercel/output/static"

# 环境变量
[vars]
CLOUDFLARE_ACCOUNT_ID = "ef96fca5011eaac8a774fcea0a71a67e"
API_TOKEN = "RY1ZaXwiKjk2YVRB2-MYXbEIY3woB_nw-VotPGKK"

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }
r2_buckets = [
  { binding = "MY_BUCKET", bucket_name = "gif-converter" }
]

# 预览环境配置
[env.preview]
vars = { ENVIRONMENT = "preview" }
r2_buckets = [
  { binding = "MY_BUCKET", bucket_name = "gif-converter" }
]