name = "gif-converter"
main = "./workers/gif-converter.js"
compatibility_date = "2023-10-26"

account_id = "ef96fca5011eaac8a774fcea0a71a67e" # Cloudflare 的 Account ID，可以在 Cloudflare Dashboard 中找到

# R2 Bucket Bindings

[[r2_buckets]]
binding = "MY_BUCKET"            # Worker 代码中使用的绑定名称（代码中引用 env.MY_BUCKET）
bucket_name = "gif-converter"     # R2 存储桶的名称，应该为 `gif-converter`
preview_bucket_name = "gif-converter" # 开发模式下使用的存储桶名称，通常与 bucket_name 保持一致

[site]
bucket = "./out"